### ISSUE TITLE
Support for diacritics

### ISSUE THREAD

**Issue by pgronkievitz** [chiefnoah/neuron-v2.vim#10]
In many languages diacritics are used and that would be cool if those were handled properly. E.g. in Polish there are just a few like `ąęćółżźń` and those are displayed as question marks. Sometimes those cause errors (but not all the time).

**Comment by chiefnoah** [comment]
Can you post a screenshot of what you're referring to?

**Comment by pgronkievitz** [comment]
![image](https://user-images.githubusercontent.com/9089064/116112649-08659380-a6b8-11eb-9a46-af007d350c72.png)
both questionmarks should be displayed as `ę`

**Comment by chiefnoah** [comment]
I believe this is an upstream issue with `neuron query`, as the text used here is sourced from that command. I created [an issue](https://github.com/srid/neuron/issues/605) on the neuron project to track this.
