### ISSUE TITLE
`gzN` and `gzn` doesn't create new file

### ISSUE THREAD

**Issue by pgronkievitz** [chiefnoah/neuron-v2.vim#12]
`gzN` and `gzn` doesn't create new file in neovim. Template's text is inserted on top of current note and inserts link. I haven't tested it in vim 8 yet

**Comment by pgronkievitz** [comment]
little update:
after a bit of investigation `l:zettel_path` seems to vanish after if statement. Possibly `neuron#add_virtual_titles()` breaks it

```viml
func! neuron#edit_zettel_new(title, ...)
	if bufname('%') != ''
		w
	endif
	let l:zettel_path = util#new_zettel_path(a:title)
	let l:zettel_id = util#zettel_id_from_path(l:zettel_path)
	echo l:zettel_id
	echo l:zettel_path
    let l:insert_new_zettel_link = get(a:, 1, 1)  " if this is commented out zettel_path exists
    if l:insert_new_zettel_link == 1
        execute "normal! i[[".l:zettel_id."]]#"
        call neuron#add_virtual_titles()
    endif

	"exec 'edit '.l:zettel_path
	"call util#add_empty_zettel_body(a:title)
	"let g:_neuron_must_refresh_on_write = 1
endf

```

**Comment by sealevel1** [comment]
@pgronkievitz do you have `set hidden` option enabled?

**Comment by pgronkievitz** [comment]
@sealevel1 I didn't, because it isn't mentioned neither in doc file nor readme. That fixes my issue, thanks!
