### ISSUE TITLE
[help] Having trouble trying to use the plugin

### ISSUE THREAD

**Issue by iGormilhit** [chiefnoah/neuron-v2.vim#15]
I'm having trouble to use the *neuron-v2* plugin. Here's my setup:

- Archlinux with kernel 5.12.1.
- neovim version `v0.4.4`.
- neuron version `1.0.1.0`.
- ag version `2.2.0`.
- fzf version `027.0`.
- the neuron-v2 pluging is installed with vim-plug, on the master branch.

Here's my minimal neovim configuration file:

```
" plugins (vim-plug)
call plug#begin('~/.config/nvim/plugged')
Plug 'arcticicestudio/nord-vim'                     " Nord color scheme
Plug 'chiefnoah/neuron-v2.vim'                   " To manage Zettlekasten the neuron way
call plug#end()

" Filetype detection
filetype plugin on

" Format indentation
if has("autocmd")
  filetype plugin indent on
endif

" Python provider in a pyenv
let g:python3_host_prog='/home/igor/.pyenv/versions/neovim3/bin/python'

set hidden

" Syntax coloration and color theme
syntax enable
set background=dark
colorscheme nord
```

I've started a zettlekasten in the following directory: `/home/igor/ecriture/fiches-test/`. I've created an empty `neuron.dhall` (but tried also the populate it, with no major behavior change), and two zettle with the help of neuron: `ab029c4.md` and `index.md`.

When opening any zettle with neovim, I don't see any change in interface, and when entering `gzz` I can see the message `Waiting until cache is populated…`. With `gzr` I have error such as:

```
Erreur détectée en traitant function <SNR>194_refresh_cache_callback_nvim[1]..<SNR>194_refresh_cache_callback :
ligne    4 :                                                                                                  
E474: Attempt to decode a blank string
Appuyez sur ENTRÉE ou tapez une commande pour continuer
```
Here is a screenshot:

![ksnip_20210509-105636](https://user-images.githubusercontent.com/1557213/117574932-24613000-b0cf-11eb-9a54-dde6324003cd.png)

Eventually the fuzzy search is then appearing, but there nothing to be search, the search result list is empty.

I'm aware of issue https://github.com/chiefnoah/neuron-v2.vim/issues/8 but as I understand, I'm using the master branch with the https://github.com/chiefnoah/neuron-v2.vim/pull/9 merged into it.

I do think that I'm doing something wrong, but cannot find out what.

**Comment by disschnarch** [comment]
having also the problem with the message

> Waiting until cache is populated…

should note that i am using spacevim

**Comment by chiefnoah** [comment]
You need a newer version of neuron. This plugin is for the neuron v2 format and address [this issue](https://github.com/fiatjaf/neuron.vim/issues/62). Please update neuron or use the [upstream plugin](https://github.com/fiatjaf/neuron.vim) instead.

**Comment by iGormilhit** [comment]
Ok, thanks for your answer. I thought that neuron v2 was the latest release, but now I understand it is not. I tried to install neuron v2 with nix, but it used 6 Go of disk space and failed. I will have to dig a bit further, obviously.

**Comment by chiefnoah** [comment]
I think the nix packages are broken right now, so the latest binary release is way out of date compared to the nix packages. I believe the v2 format was (confusingly) introduced in [`1.9.6.5`](https://github.com/fiatjaf/neuron.vim/issues/62#issuecomment-766936127). Perhaps fixing the binary builds should be prioritized? My `/nix` folder is 15G. Storage usage like that is prohibitive for use on older and cheap hardware where storage is limited.

@srid thoughts?
