### ISSUE TITLE
Installation instructions point to wrong project

### ISSUE THREAD

**Issue by vcavallo** [chiefnoah/neuron-v2.vim#3]
```
Plug 'junegunn/fzf.vim'
Plug 'fiatjaf/neuron.vim'
```

Isn't `'fiatjaf/neuron.vim'` the upstream repo and therefore the wrong project to install if one wants to use this?

**Comment by srid** [comment]
fwiw, I just use nix to manage this plugin in neovim.  https://github.com/srid/nix-config/commit/001033f0dd7cb46fc76b23a71f24abae698e3d5e

**Comment by YamiteruXYZ** [comment]
How do I install this plugin using Plug?

**Comment by vcavallo** [comment]
> How do I install this plugin using Plug?

I believe it is:

```
Plug 'junegunn/fzf.vim'
Plug 'chiefnoah/neuron-v2.vim'
```

And make sure any previous `neuron.vim` is not present. Reply here if you're not sure how to do that.
