### ISSUE TITLE
`gzn`  inserts a link to the newly-created note

### ISSUE THREAD

**Issue by vcavallo** [chiefnoah/neuron-v2.vim#5]
If your cursor is resting in a file, when using `gzn` to create a new note, a link to the new note is inserted in that file. Is this expected behavior? I appreciate the philosophy of always linking to a new note from an existing one - is that the goal of this functionality? If so, is there a way to opt-out of that and create a new, unlinked note? (aside from using `neuron new`)

**Comment by chiefnoah** [comment]
This is the intended behavior, however I think it may be worthwhile to have a way to create a new zettel without inserting a link in the current buffer.
