### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by the-yamiteru** [chiefnoah/neuron-v2.vim#8]
When I hit `gzn` in a neuron directory I see this:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/34185465/109730823-698e5080-7bba-11eb-8e48-349a8c277c18.png">

Also when I hit `gzz` I see only `Waiting until cache is populated...` which never finishes.

It's a fresh installation of neovim through homebrew. This is my init.vim

```
call plug#begin()

Plug 'junegunn/fzf.vim'
Plug 'chiefnoah/neuron-v2.vim'

call plug#end()
```

I've installed all the dependencies mentioned in the docs.

What am I doing wrong?

**Comment by jrekier** [comment]
I'm running into the same problem with `gzn`. Looks like `gzz` works fine, though.

**Comment by srid** [comment]
I'm not familiar enough with Vimscript to quickly diagnose the issue, but you can also use the following from within vim to create a new zettel:

```vim
:args `neuron new`
```

**Comment by jrekier** [comment]
Thanks. 
I have noticed a difference in the call to neuron's `edit_zettel_new()` in neuron-v2.vim which reads:

`<Plug>EditZettelNew :<C-U>call neuron#edit_zettel_new('')<cr>`

while in the original neuron.vim reads:

`<Plug>EditZettelNew :<C-U>call neuron#edit_zettel_new()<cr>`

Notice the presence of an empty string in the argument in `neuron-v2.vim`

@srid I think this might be a clue to fix the call to neuron in vim...

**Comment by chiefnoah** [comment]
@the-yamiteru can you confirm this works now after updating?

Thanks @lbiaggi for the PR!
